spring.data.mongodb.uri=mongodb+srv://ashishunhale1420_db_user:PdkaSguegT36b8A0@cluster0.f0u1sly.mongodb.net/cachar_complaints?retryWrites=true&w=majority&appName=Cluster0
logging.level.com.cachar.complaint=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
